USE TRAINING_SAMPLE;


DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS USER;



CREATE TABLE IF NOT EXISTS USER (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS ADDRESS (
    user_id BIGINT(19),
    street_no VARCHAR(50) NOT NULL,
	area_name VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id)
)  ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS CONTACT (
    user_id BIGINT(19),
    phone_number VARCHAR(16) NOT NULL,
	email_id VARCHAR(50) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id)
)  ENGINE=INNODB;


