USE TEST;
CREATE TABLE IF NOT EXISTS SERVICE_STATION (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    contact VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    age INT(3) NOT NULL,
    contact VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS CUSTOMER (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    emp_id BIGINT(19) NOT NULL,
    name VARCHAR(50) NOT NULL,
    age INT(3) NOT NULL,
    contact VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (emp_id)
        REFERENCES EMPLOYEE (id)
);

CREATE TABLE IF NOT EXISTS VEHICLE (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    service_charge INT(5) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS INVOICE (
    id BIGINT(19) NOT NULL AUTO_INCREMENT,
    name_of_owner VARCHAR(50) NOT NULL,
    vehicle_id BIGINT(19) NOT NULL,
    emp_id BIGINT(19) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL,
    service_charge INT(5) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (emp_id)
        REFERENCES EMPLOYEE (id),
    FOREIGN KEY (vehicle_id)
        REFERENCES VEHICLE (id)
);

SELECT 
    *
FROM
    SERVICE_STATION;
SELECT 
    *
FROM
    EMPLOYEE;
SELECT 
    *
FROM
    CUSTOMER;
SELECT 
    *
FROM
    VEHICLE;
SELECT 
    *
FROM
    INVOICE;


DROP TABLE SERVICE_STATION;
DROP TABLE CUSTOMER;
DROP TABLE INVOICE;
DROP TABLE VEHICLE;
DROP TABLE EMPLOYEE;
DROP DATABASE TEST;
